server:
  port: 8075

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jwtapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

steadypim:
  openapi:
    dev-url: http://localhost:8075
    prod-url: https://steadypim-api.com